spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/javaspringboot
    username: javaspringboot
    password: javaspringboot123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
# server:
#   port: 8081
